### ISSUE TITLE
Return attributes are not outputted

### ISSUE THREAD

**Issue by jamezor** [telerik/JustDecompileEngine#15]
When a method return type has a custom attribute (as used in .NET 2.0 style asmx web service proxies generated by Visual Studio) the attribute is not outputted at all into the decompiled code.

    [return: System.Xml.Serialization.XmlElementAttribute("Result", DataType="base64Binary")]
    public byte[] Render(...) {
    ...
    }

Mono.Cecil decompiles this custom attribute correctly and holds the data in `MethodReturnType.CustomAttributes` on the relevant `MemberDefinition`, but then `AttributeWriter` does not look at this at all so nothing is written out.

**Comment by adimitrov93** [comment]
Fixed by e450445
