### ISSUE TITLE
ImplAttributes are not output

### ISSUE THREAD

**Issue by jamezor** [telerik/JustDecompileEngine#16]
If you have a method with a MethodImpl attribute (such as Synchronized) it does not appear in the output from JustDecompile.

    [MethodImpl(MethodImplOptions.Synchronized)]
    public void VeryImportantToOnlyRunThisInASingleThreadedManner()
    ...

**Comment by adimitrov93** [comment]
Commits 95443da and fc372c5 fix this issue.

**Comment by adimitrov93** [comment]
86e6b8a also fixes this issue.
