### ISSUE TITLE
Cannot Decompile ASP.NET Core MVC Razor Precompiled Views

### ISSUE THREAD

**Issue by MisterJames** [telerik/JustDecompileEngine#17]
I am using the new ASP.NET Core 1.1 tooling and the following packages:
```
Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Design
Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Tools
```

These help enable a scenario where you can precompile your views in ASP.NET Core MVC 1.1, as detailed [here](https://blogs.msdn.microsoft.com/webdev/2016/11/16/announcing-asp-net-core-1-1/). 

The output is a DLL named `ProjectName.PrecompiledViews.DLL` in the root of the `PublishOutput` folder (by default) in the `bin/Release` directory. This DLL cannot be inspected by JustDecompile, with the following error message being displayed:

`JustDecompile supports only valid CLR assemblies. Not supported files(s):` with the name of the DLL above.

**Comment by tsviatko** [comment]
I haven't checked out on Core 1.1 yet but I wonder what is the chance JD got this one right. Could you run ILDASM on that assembly and see what the result is?

**Comment by VahidN** [comment]
@MisterJames I had the same problem with ILSpy too. Just deleted its related `.pdb file` and then it could decocmpile it.

**Comment by tsviatko** [comment]
Fixed now.
