### ISSUE TITLE
there may contain some error while resolving dlls when using Reflexil

### ISSUE THREAD

**Issue by Neutron3529** [telerik/JustDecompileEngine#18]
i get an error message on saving the .dll:

Reflexil is unable to save this assembly:Failed to resolve assembly: 'UnityEngine, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'

I put UnityEngine.dll and Assembly-CSharp.dll I want to modified in the same directory and load them both in JustDecompile but while saving, the same error occurs.

I don't know why, neither how to deal with such thing

but what's strange, only a few game cannot be modified due to this error message, but for most of the game made with unity, Reflexil and JD works fine

**Comment by tsviatko** [comment]
Reflexil is not maintained by the JustDecompile team. Please, try notifying the Reflexil team.
