### ISSUE TITLE
Properties replaced with methods in decompilation

### ISSUE THREAD

**Issue by dmitsov** [telerik/JustDecompileEngine#21]
Hi, we've discovered another problem with the decompiled 
Some property calls are written as methods instead of properties.
Example:
`startValue.set_x(startValue.get_x() + changeValue.get_x() * (float)num);`

Should be:
` startValue.x = startValue.x + changeValue.x * (float)num;`

**Comment by adimitrov93** [comment]
This is usually observed, when the property (in this case `startValue` and `changeValue`) is defined in another assembly and JustDecompile was not able to find it (i.e. it was not found right beside the decompiled assembly or it was not resolved though the UI). Is this the case? If not, would it be possible that you create and attach sample project and/or assembly reproducing this behavior?

**Comment by tsviatko** [comment]
Closing this issue since due to long period of inactivity.
