### ISSUE TITLE
Cannot decompile DOTween DLLs with JustDecompileEngine

### ISSUE THREAD

**Issue by TriEdgeAI** [telerik/JustDecompileEngine#25]
https://github.com/Demigiant/dotween

**Comment by adimitrov93** [comment]
Would it be possible to elaborate some more on the exact problem? A concrete problem (exception) with attached assembly (needed for reproduction) would be sufficient.

**Comment by tsviatko** [comment]
Closing this issue. We are unable to proceed without further information and there has been a long period of inactivity.
