### ISSUE TITLE
SystemInformationHelpers references missing file CommonAssemblyInfo.cs

### ISSUE THREAD

**Issue by Psychlist1972** [telerik/JustDecompileEngine#27]
It's looking for CommonAssemblyInfo.cs in the same location as CommonVersionAssemblyInfo.cs

This is my first time downloading the project.

After removing that, there's an issue with the missing strong name key, but that's workable. I didn't bother looking beyond that.

**Comment by adimitrov93** [comment]
Thank you for taking the time to report this.

We're already looking into it and it should be fixed soon.

**Comment by adimitrov93** [comment]
Fixed. You can now pull the latest source and it should build without any problems.
