### ISSUE TITLE
CS0184 - the given expression is never of the provided type

### ISSUE THREAD

**Issue by henrygab** [telerik/JustDecompileEngine#33]
https://github.com/telerik/JustDecompileEngine/blob/f0b66c2fbe6beaac6644842c3c5b9b212dd0f601/Cecil.Decompiler/Languages/BaseImperativeLanguageWriter.cs#L1022

Possibly a typo in the variable name (should it be `parameterType` instead of `parameter`?  I have no test case that causes this to result in a different decompiled source...

**Comment by adimitrov93** [comment]
Closed by #34
