### ISSUE TITLE
StyleCop-friendly decompiled sources?

### ISSUE THREAD

**Issue by henrygab** [telerik/JustDecompileEngine#35]
As a simple example, some field names use underscores.
Can you help me by ...

1. pointing to location(s) in the code where the name of variables, fields, methods, etc. is determined and stored?

2. providing recommendations for how to format pull requests, if the change is larger?
(e.g., one large squashed commit, or lots of tiny commits?)
 
Long-term, I'd love to be able to reduce the number of issues found by a default StyleCopAnalyzer analysis on a generated (decompiled) solution.

Thanks!

**Comment by adimitrov93** [comment]
Sure, I will help you.

Firstly, I would like to point out that many of those names (if not all, depending if there is a PDB for the assembly) are taken straight from the assembly and are outputted as is, i.e. they are not (and should not be) changed. In rare cases JustDecompile creates fields and methods, which does not have counterpart in the original assembly and name them appropriately (in some cases those names contain underscores, yes). Based on the occurrence frequency of those cases and the amount of work needed from both sides - yours and ours - the cost-benefit analysis tells us it's not really worth it.

That's really from on-top-of my head. If you have example, demonstrating I'm wrong, please, let me know.

**Comment by henrygab** [comment]
Thank you.
