### ISSUE TITLE
Extract the MSBuildProjectCreator in to a separate library

### ISSUE THREAD

**Issue by vincpa** [telerik/JustDecompileEngine#4]
The MSBuildProjectCreator would be useful as a library with an API to create Visual Studio projects.

There would be several use cases for it like template generation.

What do you think?

**Comment by tsviatko** [comment]
That sounds like a good idea. 

If you plan on doing this we'll gladly assist with any information you might need.

If you mean that we do it then, please, post this to our [uservoice](http://justdecompile.uservoice.com) and we'll prioritize it based on the votes it gets.
