### ISSUE TITLE
Is it possible to run JustDecompile only in .Net 4.0 instead of 4.5? What should need be done for that?

### ISSUE THREAD

**Issue by davilimaalves** [telerik/JustDecompileEngine#41]
Is it possible to run JustDecompile only in .Net 4.0 instead of 4.5? What should need be done for that?
I would like to have it on .Net 4.0 or run the ConsoleRunner with .Net 4.0
Best Regards,

**Comment by adimitrov93** [comment]
It's not officially supported, but it may be possible to be run against .NET 4.0. However, changes to the code base may be required and rather unfortunately I'm not able to guide you though the process.
