### ISSUE TITLE
VS2015/Azure won't run

### ISSUE THREAD

**Issue by mark2011** [telerik/JustDecompileEngine#7]
Brand new azure visual studio vm with vs 2015 community. Used git clone, set start up
to console runner, tried to build and run.

No errors reported, but still console runner will not run.
39 warnings reported. 2 from build, others must be from intellisense.

The 2 build warnings follow. Maybe they are serious enough to prevent complete build?

Thanks,
Mark

*Severity	Code	Description	Project	File	Line*
*Warning		The referenced component 'JustDecompile.Settings' could not be found.	JustDecompiler		*
*Warning		The referenced component 'Telerik.Baml' could not be found.	Tools.MSBuildProjectBuilder *

**Comment by adimitrov93** [comment]
Hi Mark,

No, this 2 build warnings cannot prevent complete build (tested on the same configuration as yours). Please, make sure that you run the project without debugging (i.e. Ctrl + F5). If you run it with debugging (F5) there is a chance that the console shows and instantaneously hides.

If you need

**Comment by mark2011** [comment]
Well, today after I restarted the vm, the problem is gone. Yesterday it refused to create the ConsoleRunner.exe file. Thanks for your help. Mark.
