### ISSUE TITLE
Excess code generated for lambdas

### ISSUE THREAD

**Issue by craig-wagner** [telerik/JustDecompileEngine#9]
I hope this is the right place to report this. Please let me know if there is a better location.

I have the following line of code in my C# application:

    ArgumentHelpers.ThrowIfNullOrWhitespace(() => queueName);

JustDecompile shows the following decompilation:

    ArgumentHelpers.ThrowIfNullOrWhitespace(new Expression<Func<string>>[] { Expression.Lambda<Func<string>>(Expression.Field(Expression.Constant(variable, typeof(SubscriptionInfoBase.<>c__DisplayClass17_0)), FieldInfo.GetFieldFromHandle(typeof(SubscriptionInfoBase.<>c__DisplayClass17_0).GetField("queueName").FieldHandle)), new ParameterExpression[0]) });

ILSpy shows the following decompilation:

	ArgumentHelpers.ThrowIfNullOrWhitespace(new Expression<Func<string>>[]
	{
		() => queueName
	});

It would be nice if JustDecompile generated the more concise syntax.

**Comment by tsviatko** [comment]
Well, you could try debugging this issue yourself using the code in this repository. We'll gladly review a pull request containing the fix.

If you'd like us to put this issue on our backlog, please, report it here http://www.telerik.com/forums/justdecompile/general-discussions and mail the assembly where that occurs to tsviatko.yovtchev at telerik.com.
